-- 코드를 입력하세요

SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
LEFT JOIN
    (SELECT
        BOOK_ID,
        SUM(SALES) AS SALES
     FROM
        BOOK_SALES
     WHERE
        SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
     GROUP BY
        BOOK_ID
    ) AS S
ON
    S.BOOK_ID = B.BOOK_ID
LEFT JOIN
    AUTHOR AS A
ON
    A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY
    B.CATEGORY, B.AUTHOR_ID
ORDER BY
    B.AUTHOR_ID,
    B.CATEGORY DESC