-- 코드를 입력하세요
SELECT
    YEAR(A.SALES_DATE) AS YEAR,
    MONTH(A.SALES_DATE) AS MONTH,
    B.GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM
    ONLINE_SALE AS A
JOIN
    USER_INFO AS B ON A.USER_ID = B.USER_ID
GROUP BY
    YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), B.GENDER
HAVING
    B.GENDER IS NOT NULL
ORDER BY
    YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), B.GENDER