-- 코드를 입력하세요
SELECT
    P.PRODUCT_CODE,
    O.SALES_AMOUNT * P.PRICE AS SALES
FROM
    PRODUCT AS P
JOIN
    (SELECT
        SUM(SALES_AMOUNT) AS SALES_AMOUNT,
        PRODUCT_ID
     FROM
        OFFLINE_SALE
     GROUP BY
        PRODUCT_ID
    ) AS O
ON
    O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY
    SALES DESC,
    P.PRODUCT_CODE;