-- 코드를 입력하세요
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    R.REVIEW_SCORE
FROM
    REST_INFO AS I
LEFT JOIN
    (SELECT
        REST_ID,
        ROUND(AVG(REVIEW_SCORE), 2) AS REVIEW_SCORE
     FROM
        REST_REVIEW
     GROUP BY
        REST_ID
    ) AS R
ON
    I.REST_ID = R.REST_ID
WHERE
    I.ADDRESS LIKE ("서울%") AND
    R.REVIEW_SCORE IS NOT NULL
ORDER BY
    R.REVIEW_SCORE DESC,
    I.FAVORITES DESC