-- 코드를 입력하세요
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (
    SELECT
        COUNT(DISTINCT USER_ID)
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
), 1) AS PUCHASED_RATIO
FROM
    USER_INFO AS U
JOIN
    (SELECT
        USER_ID,
        SALES_DATE
     FROM
        ONLINE_SALE
    ) AS O
ON
    O.USER_ID = U.USER_ID
WHERE
    YEAR(U.JOINED) = 2021
GROUP BY
    YEAR(O.SALES_DATE),
    MONTH(O.SALES_DATE)
ORDER BY
    YEAR(O.SALES_DATE),
    MONTH(O.SALES_DATE)