-- 코드를 입력하세요
SELECT
    U.USER_ID,
    U.NICKNAME,
    B.PRICE
FROM
    USED_GOODS_USER AS U
LEFT JOIN
    (SELECT
        WRITER_ID,
        SUM(PRICE) AS PRICE
     FROM
        USED_GOODS_BOARD
     WHERE
        STATUS = "DONE"
     GROUP BY
        WRITER_ID
    ) AS B
ON
    B.WRITER_ID = U.USER_ID
WHERE
    B.PRICE >= 700000
ORDER BY
    PRICE;