-- 코드를 입력하세요
SELECT
    B.CATEGORY,
    SUM(S.TOTAL_SALES) AS TOTAL_SALES
FROM
    BOOK AS B
LEFT JOIN
    (SELECT
        BOOK_ID,
        SUM(SALES) AS TOTAL_SALES
     FROM
        BOOK_SALES
     WHERE
        SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
     GROUP BY
        BOOK_ID
    ) AS S
ON
    S.BOOK_ID = B.BOOK_ID
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY
    